services:
  mongodb:
    image: mongo:6
    container_name: mid_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - midnet
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: midterm_nodejs-backend
    container_name: mid_backend
    depends_on:
      - mongodb
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongodb:27017/midterm_db
      - JWT_SECRET=supersecretkey
    ports:
      - "4000:4000"
    networks:
      - midnet
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:                         
        - REACT_APP_API_URL=http://localhost:4000
    image: midterm_nodejs-frontend
    container_name: mid_frontend
    depends_on:
      - backend
    ports:
      - "3001:80"
    networks:
      - midnet
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  midnet:
    driver: bridge
